language: node_js
node_js:
  - "10"
services: mongodb
cache:
  directories:
  - node_modules
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
jobs:
  include:
    - stage: "Testing"
      script: npm test
      if: branch = master