language: node_js
node_js:
  - "10"
services: mongodb
cache:
  directories:
  - node_modules
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
install:
  - npm install -g codecov
  - npm install -g istanbul
  
jobs:
  include:
    - stage: "Coverage"
      script:
        - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
        - codecov
      if: branch = master
    - stage: "Testing"
      script: npm test
      if: branch = master